spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:https://configserver-microservice.onrender.com"
  cloud:
    config:
      enabled: true
      fail-fast: true
      request-read-timeout: 10000
      request-connect-timeout: 10000
      retry:
        max-attempts: 15
        initial-interval: 2000
        multiplier: 1.5
        max-interval: 10000
<<<<<<< HEAD



=======
>>>>>>> cd69d5bebe03198f8ddd92fd79d7ceb6ec665706


